version: '3.8'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: questin-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
