from abc import ABC
from services.service_utils import num_tokens_from_string
import requests
import numpy as np

class Base(ABC):
    def __init__(self, key, model_name):
        pass
    
    def similarity(self, query: str, texts: list):
        raise NotImplementedError("Please implement similarity method!")
    
class OpenAI_APIRerank(Base):
    def __init__(self, key, model_name, base_url):
        self.base_url = base_url
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {key}"
        }
        self.model_name = model_name.split("___")[0]
        
    def similarity(self, query: str, texts: list):
        data = {
            "query": query,
            "documents": texts
        }
        token_count = 0
        for t in texts:
            token_count += num_tokens_from_string(t)
        res = requests.post(self.base_url, headers=self.headers, json=data).json()
        rank = np.zeros(len(texts), dtype=float)
        if "data" not in res:
            raise ValueError("response not contains results\n" + str(res))
        for d in res["data"]:
            rank[d["index"]] = d["relevance_score"]
            
        min_rank = np.min(rank)
        max_rank = np.max(rank)
        
        if max_rank - min_rank != 0:
            rank = (rank - min_rank) / (max_rank - min_rank)
        else:
            rank = np.zeros_like(rank)
        
        return rank, token_count
    
if __name__ == '__main__':
    model = OpenAI_APIRerank(key="asdasd", model_name="itdainb/PhoRanker", base_url="http://questin:8000/rerank")
    query = "Cơ sở vật chất tại Hòa Lạc như thế nào? Môi trường sinh hoạt ra sao?"
    sentences = [
        "\r\n- Phát triển giáo dục đào tạo và nghiên cứu khoa học vị nhân sinh, là nguồn cung ứng nhân lực chất lượng cao và tri thức khoa học công nghệ quan trọng phục vụ cho mục tiêu phát triển bền vững kinh tế xã hội của đất nước.\r\n- Từng bước mở rộng quy mô và cơ sở vật chất phục vụ đào tạo và nghiên cứu của Nhà trường tại Khu đô thị đại học Hòa Lạc.\r\n- Hướng đến thực hiện 17 mục tiêu phát triển bền vững của Liên hợp quốc tại Việt Nam (SDGs), bao gồm: 1: Xóa nghèo, 2: Không còn nạn đói, 3: Sức khỏe và có cuộc sống tốt, 4: Giáo dục có chất lượng, 5: Bình đẳng giới, 6: Nước sạch và vệ sinh, 7: Năng lượng sạch với giá thành hợp lý, 8: Công việc tốt và tăng trưởng kinh tế, 9: Công nghiệp, sáng tạo và phát triển hạ tầng, 10: Giảm bất bình đẳng, 11: Các thành phố và cộng đồng bền vững, 12: Tiêu thụ và sản xuất có trách nhiệm, 13: Hành động về khí hậu, 14: Tài nguyên và môi trường biển, 15: Tài nguyên và môi trường trên đất liền, 16: Hòa bình, công lý và các thể chế mạnh mẽ, 17: Quan hệ đối tác vì các mục tiêu.",
        "\r\nXưởng sản xuất thử nghiệm của Viện Vi sinh vật và Công nghệ Sinh học tại Hòa Lạc, nơi sinh viên thực tập về lên men và phát triển sinh phẩm.\r\nTrung tâm Nông nghiệp Nhiệt đới Quốc tế (CIAT): Sinh viên có thể tham gia thực tập các dự án về Nông nghiệp Kỹ thuật số và Vi sinh Nông nghiệp tại CIAT - một trung tâm đa quốc gia có trụ sở tại Hà Nội, Việt Nam. Môi trường thực tập tại CIAT là đa văn hóa và chuyên nghiệp, sử dụng tiếng Anh làm ngôn ngữ giao tiếp.\r\n\r\nCác doanh nghiệp hợp tác với Khoa Công nghệ Nông nghiệp:\r\n\r\nCông ty CP Giải pháp Thời tiết và Nông nghiệp (AgriMedia), Viện Công nghệ Xanh (GREENTECH), Công ty Môi trường AGBiotech, Công ty VinEco (Tập đoàn Vingroup), Công ty Nấm Long Hải, Công ty Hoa Á Châu, và các doanh nghiệp khác.",
        "\r\nSinh viên đi thực tế ở Doanh nghiệp VinEco Tam Đảo\r\nSinh viên đi thực tế thăm công ty TNHHSX Bejo Việt Nam – doanh nghiệp sản xuất và kinh doanh hạt giống rau Hà Lan\r\nSinh viên đi thực tế thăm Công ty TNHH Dalat Hasfarm – công ty tiên phong trong việc phát triển nghề trồng hoa chuyên nghiệp tại Việt Nam\r\nSinh viên đi thực tế thăm các mô hình hộ liên kết sản xuất theo tiêu chuẩn VietGAP\r\nĐa dạng công việc cho sinh viên sau khi tốt nghiệp\r\nSau khi ra trường, sinh viên có thể làm việc ở các cơ quan, doanh nghiệp thuộc khối nhà nước và tư nhân: Doanh nghiệp sản xuất, kinh doanh nông sản, thực phẩm và thiết bị, vật tư nông nghiệp;",
        "- Được đưa vào sử dụng từ năm 2023, cơ sở vật chất tại Hòa Lạc không chỉ mới mẻ mà còn được trang bị đầy đủ tiện nghi hiện đại, sẵn sàng phục vụ cho việc học tập và sinh hoạt của sinh viên:\r\n- Ký túc xá có khoảng không gian rộng rãi, sạch sẽ và được trang bị đầy đủ trang thiết bị phục vụ sinh hoạt và học tập.\r\n- Trong khuôn viên ký túc xá có đầy đủ nhà ăn, siêu thị, dịch vụ giặt là, hỗ trợ y tế… và điều đặc biệt là rất gần với khu giảng đường giúp sinh viên dễ dàng hơn trong việc đi lại.\r\n- Môi trường sinh hoạt đóng vai trò quan trọng trong trải nghiệm của sinh viên, vì vậy việc xây dựng một môi trường tích cực là rất cần thiết để giúp các bạn phát triển toàn diện về mọi mặt trong cuộc sống.",
        " Trong quá trình học, sinh viên sẽ tạo lập các năng lực như: tư duy logic, nghiên cứu, sáng tạo.\r\nVị trí việc làm: Sinh viên tốt nghiệp ngành Kỹ thuật Điều khiển và Tự động hóa sau khi ra trường có thể làm việc ở những vị trí như sau:\r\n- Kỹ thuật viên trong các cơ quan tổ chức quản lý, phát triển và ứng dụng điều khiển và Tự động hóa trong và ngoài nước.\r\n- Các Viện, Trung tâm nghiên cứu, trường Đại học như: Nghiên cứu viên tại Viện Nghiên cứu Điện tử – tin học – Tự động hóa, Viện Ứng dụng công nghệ, Trung tâm thiết kế vi mạch, các Khu công nghệ cao.",
        "\r\nCác định hướng đào tạo:\r\n- Thủy khí công nghiệp và môi trường\r\n- Cơ học kỹ thuật biển\r\n- Công nghệ vũ trụ\r\n- Vật liệu và kết cấu tiên tiến\r\nCơ hội việc làm sau khi ra trường:\r\n- Cán bộ nghiên cứu, thiết kế, chế tạo, quản lý sản xuất tại các nhà máy của các doanh nghiệp, tập đoàn trong nước và quốc tế có liên quan đến lĩnh vực cơ khí\r\n- Kỹ sư ra trường có thể làm việc tại các cơ quan quản lý, các cơ sở công nghiệp, các dự án môi trường, các viện nghiên cứu và các trường đại học; có nhiều cơ hội chuyển tiếp đào tạo bậc sau đại học và NCKH ở trong và ngoài nước.",
        " Hola chính là một môi trường như vậy, một \"môi trường xanh\" đúng nghĩa với không khí trong lành và yên tĩnh, mang lại những lợi ích về cả mặt tinh thần cũng như phát triển thể chất cho toàn bộ sinh viên theo học. Bên cạnh đó, môi trường sinh hoạt tập thể này cũng tạo điều kiện để sinh viên gặp gỡ, gắn kết và học hỏi lẫn nhau. \r\n\r\n\r\nNgành Trí tuệ Nhân tạo là ngành đào tạo mũi nhọn tại Trường Đại học Công nghệ, với sự hợp tác từ các doanh nghiệp hàng đầu như Công ty cổ phần VNG, Samsung Electronics Việt Nam, và FPT Software. Sinh viên theo học sẽ có cơ hội tham gia các dự án nghiên cứu và thực tập tại các công ty này.",
        " Sinh viên được tiếp cận thực tế, thực hành, thực tập tại các phòng thực hành của Trường, Viện máy và dụng cụ công nghiệp (IMI), Viện Nghiên cứu Cơ khí (NARIME) với hệ thống trang thiết bị hiện đại.\r\n\r\n\r\nĐiều 21. Xây dựng và thực hiện quy chế của cơ sở đào tạo\r\n1. Căn cứ Quy chế này và các quy định hiện hành khác có liên quan, hiệu trưởng cơ sở đào tạo có trách nhiệm:\r\na) Chỉ đạo xây dựng, ban hành và tổ chức thực hiện quy chế đào tạo của cơ sở đào tạo trên cơ sở tư vấn của hội đồng khoa học và đào tạo và các quy định quản lý nội bộ;",
        "\r\nMôi trường học tập:\r\n- Thực tập, nghiên cứu và tiếp cận thực tế tại các phòng thực hành hiện đại của trường, các cơ sở nghiên cứu liên kết về công nghệ nano.\r\n- Nắm được nguyên lý vận hành để tư vấn, giám sát, phụ trách kỹ thuật thiết kế điều khiển lắp ráp các sản phẩm trong sản xuất công nghiệp, xét nghiệm ở các bệnh viện hay phân loại kiểm định chất lượng sản phẩm, phân tích vật liệu.\r\n- Trang bị các kiến thức cơ bản về vật lý, khoa học vật liệu, công nghệ thông tin và điện tử.\r\n- Trang bị các kiến thức chuyên sâu trong lĩnh vực vật liệu mới, vi điện tử, Y Sinh, môi trường và năng lượng sạch.",
        "5 năm vì:\r\n- Tính đặc thù ngành học: Đây là các ngành đòi hỏi sinh viên phải có thời gian thực hành dài hơn, đặc biệt trong phòng thí nghiệm hoặc ngoài thực địa.\r\n- Cơ hội học tập chuyên sâu: Thời gian đào tạo dài hơn cho phép tích hợp các học phần nghiên cứu và ứng dụng thực tế, đảm bảo sinh viên không chỉ nắm vững lý thuyết mà còn thành thạo kỹ năng thực hành.\r\n- Học tập tại Hòa Lạc: Khu Hòa Lạc được trang bị cơ sở vật chất hiện đại, phục vụ tốt cho các ngành công nghệ cao và đặc thù, đòi hỏi thời gian đào tạo kéo dài để tận dụng tối đa cơ sở này.",
        "..\r\nBên cạnh đó, chương trình đào tạo được sử dụng các trang thiết bị hiện đại của PTN kỹ thuật hạ tầng của Đại học Việt Nhật, Phòng Thực hành của Khoa Cơ kỹ thuật, các PTN của các đối tác lớn trên địa bàn Hà Nội.\r\nKhông chỉ gắn đào tạo với nghiên cứu và công bố quốc tế, sinh viên còn được thực tập sâu tại các cơ quan, doanh nghiệp trong lĩnh vực này để có kỹ năng làm việc ngay sau khi  tốt nghiệp. Nhà trường cam kết 100% sinh viên khi ra trường có việc làm.\r\nCác hướng đào tạo và nghiên cứu chính của khoa trong lĩnh vực này gồm:\r\n- Vật liệu và kết cấu tiên tiến ứng dụng trong xây dựng, giao thông và hạ tầng\r\n",
        " khả năng thiết kế, chế tạo, bảo trì, sản xuất, thử nghiệm, quản lý các hệ thống mạng và truyền thông máy tính.\r\n- Định hướng Khoa học máy tính và dịch vụ: Nghiên cứu và triển khai các Dịch vụ Công nghệ thông tin, đáp ứng các vấn đề về phân tích, xây dựng giải pháp nền tảng cho các dịch vụ Công nghệ thông tin và dịch vụ dựa trên Công nghệ thông tin trong thực tế; tổ chức thực hiện và quản lý được các công việc trong lĩnh vực dịch vụ Công nghệ thông tin.\r\nCơ hội việc làm sau khi ra trường:\r\n- Tỷ lệ có việc làm sau tốt nghiệp: 98% sinh viên tốt nghiệp ngành CNTT có thể làm tại các công ty công nghệ với nhiều vị trí khác nhau như:\r\n",
        " kiêm nhiệm, thuộc viện, ký hợp đồng lao động kiêm nhiệm với trường; thỉnh giảng, thuộc các đơn vị đào tạo và nghiên cứu phù hợp khác, ký hợp đồng mời giảng với trường). Cơ sở vật chất (phòng học, phòng thí nghiệm, phòng thực hành, …) cũng được quản lý bởi các đơn vị hành chính khác nhau.\r\nTrong thời gian qua, Khoa CHKT&TĐH đã không ngừng đổi mới và nâng cao chất lượng hoạt động về mọi mặt với mục tiêu trở thành một đơn vị đào tạo, nghiên cứu và triển khai khoa học công nghệ chất lượng cao, tạo ra những sản phẩm tinh hoa đáp ứng cho nhu cầu ngày càng cao của đất nước.",
        "\r\nSinh viên thực hành đo đạc các chỉ số thủy canh trong phòng thí nghiệm Công nghệ nông nghiệp\r\nSinh viên thực hành xử lý số liệu thu thập bởi máy bay không người lái\r\nSinh viên rèn nghề “từ trang trại đến bàn ăn” tại Khu thực nghiệm Công nghệ nông nghiệp Hòa Lạc\r\nMạng lưới đối tác đa dạng, sinh viên được thực tập và tiếp cận việc làm sớm\r\nKhoa Công nghệ Nông nghiệp không ngừng phát triển mạng lưới hợp tác nghiên cứu và đào tạo với nhiều đơn vị doanh nghiệp, viện nghiên cứu thực hiện mô hình Trường – Viện – Doanh nghiệp, nhằm thúc đẩy các hoạt động thực tập, thực tế cho sinh viên ngay khi còn ngồi trên ghế nhà trường, đồng thời đẩy mạnh nghiên cứu ứng dụng trong lĩnh vực công nghệ nông nghiệp.",
        "Giới thiệu:\r\n- Ngành Kỹ thuật năng lượng đào tạo kỹ sư có các kiến thức và kỹ năng về năng lượng, công nghệ kỹ thuật năng lượng, và thiết kế, chế tạo, vận hành hệ thống biến đổi và tích trữ năng lượng, quản lý và an toàn năng lượng, ứng dụng của năng lượng tái tạo trong dân sinh và công nghiệp.\r\n- Sinh viên được thực tập và tiếp cận thực tế tại các phòng thực hành hiện đại của trường, các doanh nghiệp trong nước và FDI về năng lượng.\r\n- Sinh viên tốt nghiệp có thể làm việc tại các tập đoàn công nghiệp, công ty kỹ thuật – sản xuất, cơ quan quản lý, nghiên cứu triển khai và chuyển tiếp đào tạo bậc sau đại học ở trong và nước ngoài\r\n",
        "\r\n\r\n\r\nGiải mã ngành học: CN6 - Công nghệ kỹ thuật cơ điện tử\r\nGiới thiệu:\r\n- Ngành Công nghệ kỹ thuật cơ điện tử đào tạo cử nhân có kiến thức hiện đại và liên ngành về cơ khí, điện tử, tin học công nghiệp và tự động hóa. Sinh viên tốt nghiệp có khả năng phát triển, khai thác và vận hành các hệ thống điều khiển trong công nghiệp cũng như dân dụng.\r\n- Sinh viên được tiếp cận thực tế, thực hành, thực tập tại các phòng thực hành của Trường, Viện máy và dụng cụ công nghiệp (IMI), Viện Nghiên cứu Cơ khí (NARIME) với hệ thống trang thiết bị hiện đại.\r\n- Sinh viên được trang bị các kiến thức hiện đại và liên ngành về cơ khí, điện tử, tin học trong công nghiệp và tự động hóa, các kỹ năng và năng lực nghề nghiệp cần thiết để có thể tham gia phát triển, thiết kế, chế tạo và vận hành các thiết bị cơ điện tử, dây chuyền sản xuất tự động.",
        "\r\n+ Phát triển môi trường đại học chuyên nghiệp, văn minh, hiện đại. Tạo lập được môi trường giáo dục đại học chuyên nghiệp, văn minh, hiện đại là một thể thống nhất hữu cơ của tất cả các mặt hoạt động giảng dạy, học tập, nghiên cứu và dịch vụ. Xây dựng thành công đại học số hóa và mô hình quản trị hiện đại.\r\n+ Triển khai thành công và hiệu quả mô hình tự chủ đại học.\r\n+ Mở rộng quy mô và cơ sở vật chất, hệ thống phòng thí nghiệm của Nhà trường tại Khu đô thị đại học Hòa Lạc.\r\n+ Các hoạt động của Nhà trường được gắn kết với thực hiện 17 mục tiêu phát triển bền vững của Liên hợp quốc tại Việt Nam (SDGs).",
        "- Chuyên ngành kỹ thuật máy tính\r\n- Chuyên ngành Điều khiển và tự động hóa\r\n- Chuyên ngành điện tử y - sinh\r\n- Chuyên ngành vi điện tử\r\n\r\n\r\nGiới thiệu về Khoa Cơ học Kỹ thuật và Tự động hóa\r\nKhoa Cơ học Kỹ thuật và Tự động hóa được thành lập theo Quyết định số 1279/QĐ-TCCB ngày 04 tháng 7 năm 2005 của Giám đốc Đại học Quốc Gia Hà Nội\r\nKhoa Cơ học kỹ thuật và Tự động hóa là một đơn vị đào tạo thuộc Trường ĐHCN, ĐHQG Hà Nội xây dựng và hoạt động theo mô hình phối thuộc giữa Trường ĐHCN và Viện Cơ học, Viện Công nghệ Vũ trụ, thuộc Viện KH&CN Việt Nam, tiếp đó mô hình được mở  rộng bằng kết quả  hợp tác giữa Trường ĐHCN và IMI Holding, Bộ Công thương, trên cơ sở các thỏa thuận hợp tác được ký kết giữa lãnh đạo các bên liên quan.",
        "+ 01 cán bộ hợp đồng làm việc, do Viện Cơ học trả lương, làm việc tại Viện Cơ học, phụ trách công tác quản lý đào tạo thạc sĩ Cơ kỹ thuật.\r\nCơ sở vật chất: Khoa CHKT&TĐH hiện đang có 02 cơ sở:\r\n- Cở sở 1, nằm trong khuôn viên chung của Trường ĐH Công nghệ (144 Xuân Thủy, Cầu Giấy, Hà Nội): tập trung hầu hết các hoạt động chính của Khoa bao gồm các hoạt động tổ chức hành chính, đào tạo đại học, đào tạo sau đại học, nghiên cứu khoa học và hợp tác quốc tế…;\r\n- Cơ sở 2, nằm trong khuôn viên Viện Cơ học, Viện Hàn lâm Khoa học và Công nghệ Việt Nam, phục vụ cho hoạt động đào tạo năm cuối bậc đào tạo đại học ngành Cơ học kỹ thuật và hoạt động đào tạo sau đại học ngành Cơ học kỹ thuật.",
        "Cơ hội việc làm sau khi ra trường:\r\n- Cán bộ quản lý, cán bộ kỹ thuật, chuyên viên triển khai trong các tập đoàn hoạt động liên quan đến năng lượng như: năng lượng mặt trời, gió, năng lượng sạch, năng lượng tái tạo, năng lượng truyền thống,…\r\n- Cán bộ tại các trung tâm/phòng nghiên cứu và phát triển, chuyển giao và ứng dụng công nghệ trong các tập đoàn công ty trong và ngoài nước liên quan đến năng lượng\r\n- Kiến trúc sư, quản lý, giám sát và khai thác về kỹ thuật liên quan đến năng lượng điện trong các dự án xây dựng\r\n- Giảng viên và nghiên cứu viên tại các trường đại học và Viện nghiên cứu\r\n",
        "\r\n- Động lực học, điều khiển và cơ khí hàng không.\r\nCơ hội việc làm sau khi ra trường: Sinh viên có thể đảm nhiệm các vị trí sau tại các công ty hàng không như Viettel, Vietnam Airlines, Trung tâm Vũ trụ Việt Nam:\r\n- Lập trình điều khiển,thiết kế chế tạo các thiết bị bay Công ty công nghệ sản xuất thiết bị: drone, flycam, thiết bị giao hàng, ứng dụng trong nông nghiệp: giám sát, tưới tiêu tự động (thiết bị bay không người lái), các hệ thống điều khiển, công nghệ vệ tinh, tên lửa.\r\n- Kỹ sư thiết kế, chế tạo các thiết bị bay, vệ tinh.\r\n- Kỹ sư vận hành và bảo dưỡng các thiết bị bay.",
        " địa điểm số 8 Tôn Thất Thuyết, Hà Nội. Dành cho hầu hết các ngành và thời gian học tập tại Trường Đại học Công nghệ.\r\n– Cơ sở Hoà Lạc_chỉ dành cho năm thứ nhất của một số ngành: cơ sở Đại học Quốc gia Hà Nội tại Hòa Lạc (Xã Thạch Hoà, huyện Thạch Thất, Hà Nội).\r\n\r\n\r\nGiới thiệu trường đại học Công Nghệ, đại học Quốc gia Hà Nội\r\nĐại học Công Nghệ tên tiếng anh là UET (University of Engineering and Technology)\r\nTrường Đại học Công nghệ nằm trong khuôn viên của Đại học Quốc gia Hà Nội tại quận Cầu Giấy ở phía tây thành phố, ngay ngã tư của hai tuyến đường lớn: tuyến đường Phạm Hùng qua cầu vượt nối đường Phạm Văn Đồng kéo dài qua cầu Thăng Long đến sân bay quốc tế Nội Bài và tuyến đường Xuân Thủy – Hồ Tùng Mậu nối tới quốc lộ 32 đi thị xã Sơn Tây.",
        " Nhà trường cung cấp các phòng thí nghiệm hiện đại và tổ chức các cuộc thi nghiên cứu khoa học cấp trường, cấp quốc gia, giúp sinh viên phát triển ý tưởng và kỹ năng nghiên cứu. Sinh viên xuất sắc còn có cơ hội nhận học bổng và tài trợ từ các công ty đối tác để triển khai dự án của mình​\r\n\r\n\r\nSinh viên tại Trường Đại học Công nghệ có thể đăng ký học song song hai ngành. Điều kiện để đăng ký là sinh viên cần hoàn thành năm học đầu tiên với kết quả học tập từ 2.5 trở lên (thang điểm 4) và không có môn nào bị điểm F. Học song song hai ngành là cơ hội để sinh viên phát triển kiến thức liên ngành, đặc biệt với các ngành liên quan như Công nghệ Thông tin và Trí tuệ Nhân tạo\r\n",
        " Sinh viên cũng có cơ hội thực tập và làm việc trực tiếp tại các công ty đối tác ngay từ khi còn học​\r\n\r\n\r\nNgành Trí tuệ Nhân tạo trang bị cho sinh viên các kỹ năng quan trọng như lập trình thuật toán, xử lý dữ liệu lớn, học máy (machine learning), và phát triển ứng dụng trí tuệ nhân tạo. Sinh viên còn được đào tạo khả năng phân tích và giải quyết vấn đề bằng công nghệ AI trong nhiều lĩnh vực.\r\n\r\nSau khi tốt nghiệp, bạn có thể làm việc ở các lĩnh vực như:\r\n- Phát triển hệ thống AI cho các doanh nghiệp.\r\n- Xử lý ngôn ngữ tự nhiên (NLP) trong công nghệ chatbot.",
        "Vị trí việc làm sau khi ra trường:\r\n- Kỹ thuật viên trong các cơ quan tổ chức quản lý, phát triển và ứng dụng điều khiển và Tự động hóa trong và ngoài nước.\r\n- Nghiên cứu viên tại các viện, trung tâm nghiên cứu, trường đại học như Viện Nghiên cứu Điện tử – Tin học – Tự động hóa, Viện Ứng dụng công nghệ,…\r\n- Kỹ sư thiết kế, vận hành, bảo trì kỹ thuật ở các dây chuyền sản xuất hiện đại trong công nghiệp\r\n- Các doanh nghiệp tư vấn kỹ thuật, kinh doanh thiết bị tự động hoặc chuyển giao công nghệ. Nhân viên hỗ trợ kỹ thuật hoặc giới thiệu sản phẩm cho các tập đoàn sản xuất thiết bị tự động có uy tín trong nước và thế giới (Siemens, ABB, OMRON, Mitsubishi…).",
        "Môi trường học tập:\r\n- Trang bị các kiến thức nền tảng liên quan đến năng lượng như Vật lý, Vật liệu tiên tiến và linh kiện, hóa sinh học, điều khiển, …. Nắm được các quy luật, nguyên lý, bản chất và mô phỏng các quá trình chuyển hóa về năng lượng\r\n- Trang bị các kiến thức chuyên sâu như năng lượng mặt trời, bức xạ, biến đổi và tích trữ các nguồn năng lượng mới, chuyển hóa các dạng năng lượng, an toàn năng lượng, kiểm soát ô nhiễm, quản lý hiệu quả sử dụng nguồn năng lượng, chính sách năng lượng, …\r\n- Sinh viên tốt nghiệp có kiến thức chuyên môn và có khả năng ứng dụng kiến thức để thực hành tốt, ứng dụng các hiểu biết và kỹ năng thực hành để giải quyết, triển khai thực tế.",
        " văn bằng tốt nghiệp nếu đã được cấp sẽ bị thu hồi, huỷ bỏ.\r\n\r\n\r\nKỹ sư Công nghệ Nông nghiệp Kỹ thuật số: Làm việc tại các doanh nghiệp sản xuất, kinh doanh và sử dụng thiết bị nông nghiệp công nghệ cao. Công việc bao gồm thiết kế, chế tạo, lập trình, và vận hành hệ thống và thiết bị nông nghiệp tự động (ví dụ: hệ thống tưới tiêu thông minh, nhà lưới tự động).\r\n\r\nKỹ sư Công nghệ Sinh học Nông nghiệp: Làm việc trong các công ty hoặc tổ chức nghiên cứu, chuyên về nhân giống cây trồng, chế tạo chế phẩm sinh học, bảo quản và chế biến nông sản, kiểm định chất lượng nông sản.",
        "\r\n\r\n\r\nĐiểm nổi bật:\r\n– Sinh viên năm thứ nhất học tập tại cơ sở Hoà Lạc:\r\n+ 100% được học tập theo mô hình hiện đại kết hợp giảng dạy kiến thức chuyên môn và đào tạo kỹ năng mềm, được tham gia các hoạt động câu lạc bộ và các hoạt động thể thao, văn hóa.\r\n+ 100% được bố trí chỗ ở trong Ký túc xá gần khuôn viên khu học tập;\r\n+ 100% được nhận quà tặng từ Nhà trường 01 laptop (tối đa 15.000.000đ) đáp ứng nhu cầu học tập.\r\n– Từ năm thứ 2 trở đi, sinh viên sẽ phải quay trở lại học tập tại cơ sở Cầu Giấy.\r\n\r\n\r\nGhi chú\r\n",
        "\r\n- Nghiên cứu vật liệu, linh kiện mới và công nghệ năng lượng tái tạo.\r\n- Cán bộ phụ trách kỹ thuật, sản xuất trong các tập đoàn, doanh nghiệp/công ty trong và ngoài nước.\r\n- Quản lý, tư vấn, thiết kế, đánh giá, vật liệu, vận hành thiết bị kỹ thuật cao.\r\n- Chuyên viên triển khai, chuyển giao và ứng dụng phát triển sản phẩm mới.\r\n- Hỗ trợ các dự án Khoa học công nghệ và hỗ trợ tư vấn cho các bộ ngành, tổ chức.\r\n- Cơ hội tiếp tục học tập tại nước ngoài (Pháp, Nhật Bản, Hàn Quốc, Singapore,…)\r\n\r\n\r\nGiải mã ngành học: CN13 - Kỹ thuật năng lượng\r\n",
        "\r\n- Thực hành thực tế: Chương trình có tỷ lệ thực hành cao, với các dự án phát triển robot tự hành, robot công nghiệp và robot y tế.\r\n- Hợp tác doanh nghiệp: Sinh viên sẽ được thực tập tại các doanh nghiệp lớn như Samsung Electronics, LG Display, và FPT Software. Những dự án thực tập tại đây không chỉ giúp sinh viên nâng cao kỹ năng mà còn mở ra cơ hội việc làm ngay sau khi tốt nghiệp. \r\nSau khi ra trường, sinh viên ngành Kỹ thuật Robot có thể làm việc trong các lĩnh vực:\r\n- Thiết kế và chế tạo robot tại các công ty công nghệ cao.\r\n- Phát triển hệ thống tự động hóa trong sản xuất.\r\n- Nghiên cứu và ứng dụng robot trong y tế và quốc phòng."
    ]
    reranked_results = model.similarity(query, sentences)
    print(reranked_results)